<?php
/**
 * SMM Panel - Database Connection Handler (PDO MySQL)
 * Secure Server-Side Database Manager
 */

require_once __DIR__ . '/constants.php';

class Database {
    private static ?PDO $instance = null;
    
    /**
     * Get Database Credentials
     * Loaded from config/db-config.php generated by the installer
     */
    public static function getConfig(): array {
        $configFile = __DIR__ . '/db-config.php';
        if (file_exists($configFile)) {
            return require $configFile;
        }

        // Default environment variables fallback if db-config.php is not yet generated
        return [
            'host' => getenv('DB_HOST') ?: '127.0.0.1',
            'port' => getenv('DB_PORT') ?: '3306',
            'database' => getenv('DB_NAME') ?: 'smm_panel',
            'username' => getenv('DB_USER') ?: 'root',
            'password' => getenv('DB_PASS') ?: '',
            'charset' => 'utf8mb4'
        ];
    }

    /**
     * Test a set of database credentials (used during installer)
     */
    public static function testConnection(string $host, string $port, string $dbname, string $username, string $password): array {
        try {
            $dsn = "mysql:host={$host};port={$port};dbname={$dbname};charset=utf8mb4";
            $options = [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_TIMEOUT            => 5,
            ];
            $testPdo = new PDO($dsn, $username, $password, $options);
            return ['success' => true, 'message' => 'Connection established successfully!'];
        } catch (PDOException $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }

    /**
     * Get singleton PDO connection
     * Strict: Throws exception if connection fails. NO demo or bypass fallback.
     */
    public static function getConnection(): PDO {
        if (self::$instance === null) {
            $cfg = self::getConfig();
            $dsn = "mysql:host=" . $cfg['host'] . ";port=" . $cfg['port'] . ";dbname=" . $cfg['database'] . ";charset=" . ($cfg['charset'] ?? 'utf8mb4');
            $options = [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ];

            try {
                self::$instance = new PDO($dsn, $cfg['username'], $cfg['password'], $options);
            } catch (PDOException $e) {
                // If live MySQL is not configured or offline, throw explicit error
                throw new RuntimeException("Database connection error: " . $e->getMessage());
            }
        }

        return self::$instance;
    }
}
